In [1]:
import fastf1

fastf1.Cache.enable_cache("../data/cache")

In [2]:
session = fastf1.get_session(2024, "Monza", "Q")

session.load()

core           INFO 	Loading data for Italian Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '63', '16', '55', '44', '1', '11', '23', '27', '14', '3', '20', '10', '31', '22', '18', '43', '77', '24']

In [3]:
session.laps.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:16:12.142000,NOR,4,NaT,1.0,1.0,0 days 00:14:16.306000,NaT,NaT,0 days 00:00:37.116000,...,True,McLaren,0 days 00:14:16.306000,2024-08-31 14:03:14.075,1,NaN,False,,False,False
1,0 days 00:17:32.053000,NOR,4,0 days 00:01:19.911000,2.0,1.0,NaT,NaT,0 days 00:00:26.484000,0 days 00:00:26.898000,...,True,McLaren,0 days 00:16:12.142000,2024-08-31 14:05:09.911,1,NaN,False,,False,True
2,0 days 00:19:23.074000,NOR,4,0 days 00:01:51.021000,3.0,1.0,NaT,0 days 00:19:18.770000,0 days 00:00:32.371000,0 days 00:00:38.291000,...,True,McLaren,0 days 00:17:32.053000,2024-08-31 14:06:29.822,1,NaN,False,,False,False
3,0 days 00:43:29.375000,NOR,4,NaT,4.0,2.0,0 days 00:41:40.139000,NaT,NaT,0 days 00:00:39.008000,...,True,McLaren,0 days 00:19:23.074000,2024-08-31 14:08:20.843,12,NaN,False,,False,False
4,0 days 00:44:49.102000,NOR,4,0 days 00:01:19.727000,5.0,2.0,NaT,NaT,0 days 00:00:26.395000,0 days 00:00:26.865000,...,True,McLaren,0 days 00:43:29.375000,2024-08-31 14:32:27.144,1,NaN,False,,False,True

In [4]:
lap = session.laps.pick_drivers("LEC").pick_fastest().get_telemetry()
lap

,Date,SessionTime,DriverAhead,DistanceToDriverAhead,Time,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Distance,RelativeDistance,Status,X,Y,Z
2,2024-08-31 15:03:09.836,0 days 01:14:12.067000,,NaN,0 days 00:00:00,11468.635727,322.00,8,99.617857,False,8,interpolation,-0.035548,-0.000006,OnTrack,-1372.917895,-681.198488,1871.929905
3,2024-08-31 15:03:09.909,0 days 01:14:12.140000,,NaN,0 days 00:00:00.073000,11482.714286,322.00,8,99.357143,False,8,pos,6.494872,0.001126,OnTrack,-1369.000000,-619.000000,1872.000000
4,2024-08-31 15:03:09.929,0 days 01:14:12.160000,,NaN,0 days 00:00:00.093000,11486.571429,322.00,8,99.285714,False,8,pos,8.287603,0.001437,OnTrack,-1368.000000,-602.000000,1872.000000
5,2024-08-31 15:03:10.009,0 days 01:14:12.240000,,NaN,0 days 00:00:00.173000,11502.000000,322.00,8,99.000000,False,14,car,15.473889,0.002683,OnTrack,-1363.656966,-538.559027,1872.003638
6,2024-08-31 15:03:10.248,0 days 01:14:12.479000,,NaN,0 days 00:00:00.412000,11562.000000,325.00,8,100.000000,False,14,car,37.050278,0.006425,OnTrack,-1344.277325,-335.748315,1872.618098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
618,2024-08-31 15:04:28.849,0 days 01:15:31.080000,,NaN,0 days 00:01:19.013000,11324.000000,318.00,8,100.000000,False,8,car,5720.116111,0.991959,OnTrack,-1405.913803,-1069.686410,1869.720739
619,2024-08-31 15:04:28.929,0 days 01:15:31.160000,,NaN,0 days 00:01:19.093000,11347.500000,318.75,8,100.000000,False,8,pos,5727.229150,0.993193,OnTrack,-1402.000000,-1019.000000,1870.000000
620,2024-08-31 15:04:29.169,0 days 01:15:31.400000,,NaN,0 days 00:01:19.333000,11418.000000,321.00,8,100.000000,False,8,car,5748.649444,0.996907,OnTrack,-1385.443628,-817.021830,1870.750891
621,2024-08-31 15:04:29.229,0 days 01:15:31.460000,,NaN,0 days 00:01:19.393000,11417.100000,321.00,8,100.000000,False,8,pos,5754.002108,0.997836,OnTrack,-1381.000000,-763.000000,1871.000000
622,2024-08-31 15:04:29.297,0 days 01:15:31.528000,,NaN,0 days 00:01:19.461000,11416.080000,321.00,8,100.000000,False,8,interpolation,5760.065657,0.998887,OnTrack,-1376.028616,-702.172549,1871.333028

In [5]:
import matplotlib.pyplot as plt
import plotly.graph_objects as go
# graph the track as a 3d render
tel = lap

x = tel["X"] / 10   # tenths of a meter → meters
y = tel["Y"] / 10
z = tel["Z"] / 10

fig = go.Figure(
    go.Scatter3d(
        x=x,
        y=y,
        z=z,
        mode="lines",
        line=dict(
            color=tel["Speed"],
            colorscale="Plasma",
            width=5,
            colorbar=dict(
                title="Speed (km/h)",
                thickness=15,
            ),
        ),
        # This adds a hover box showing the exact speed at any point on the track
        hovertemplate="X: %{x}<br>Y: %{y}<br>Z: %{z}<br>Speed: %{text} km/h<extra></extra>",
        text=tel["Speed"],
    )
)

fig.update_layout(
    scene=dict(
        aspectmode="data",
        xaxis=dict(visible=False),
        yaxis=dict(visible=False),
        zaxis=dict(visible=False),
    ),
    title=dict(
        text="FastF1 3D Telemetry Track Map",
        x=0.5,
    ),
    margin=dict(l=0, r=0, b=0, t=40),
)

fig.show()

In [6]:
import pandas as pd
export = pd.DataFrame({
    "time":     tel["Time"].dt.total_seconds(),
    "x":        tel["X"] / 10,
    "y":        tel["Y"] / 10,
    "z":        tel["Z"] / 10,
    "speed":    tel["Speed"],
    "throttle": tel["Throttle"],
    "brake":    tel["Brake"].astype(int),
    "gear":     tel["nGear"],
})
# Make time start at 0
export["time"] = export["time"] - export["time"].iloc[0]

export.head()

    time           x          y           z  speed    throttle  brake  gear
2  0.000 -137.291789 -68.119849  187.192991  322.0   99.617857      0     8
3  0.073 -136.900000 -61.900000  187.200000  322.0   99.357143      0     8
4  0.093 -136.800000 -60.200000  187.200000  322.0   99.285714      0     8
5  0.173 -136.365697 -53.855903  187.200364  322.0   99.000000      0     8
6  0.412 -134.427733 -33.574831  187.261810  325.0  100.000000      0     8

In [8]:
export.to_csv("../data/samples/f1_monza_lec_q.csv", index=False)

In [ ]:
from telemetry.f1 import load_session